config/routes.rb
Rails.application.routes.draw do
  resources :pages
  root to: "application#index"
  mount Optimadmin::Engine => "/admin"
end
Optimadmin::Engine.routes.draw do
  resources :menu_items, except: :show do
    collection do
      #get 'update_leaf_form'
      #get 'update_tag_select'
      get 'update-link-resources'
      get 'reorder'
      post 'order'
    end
  end

  resources :static_pages
  resources :external_links, only: [:create]
end

app/models/optimadmin/external_link.rb
module Optimadmin
  class ExternalLink < ActiveRecord::Base
    has_many :menu_items, as: :menu_resource
    validates :name, presence: true, uniqueness: true

    def destination
      name
    end
  end
end

app/models/optimadmin/link.rb
module Optimadmin
  class Link < ActiveRecord::Base
    has_one :menu_item
    belongs_to :menu_resource, polymorphic: true
    validates :menu_resource_type, :menu_resource_id, presence: true

    include ActionDispatch::Routing::UrlFor
    include Rails.application.routes.url_helpers

    def self.find_item(resource_type, resource_id)
      where(resource_type: resource_type, resource_id: resource_id)
    end

    def destination
      #if resource_type == 'Optimadmin::ExternalLink'
      #  begin
      #    resource = Object.const_get("Optimadmin::#{resource_type}").find(resource_id)
      #    resource = resource.name if resource.present?
      #  rescue
      #    nil
      #  end
      #elsif resource_type == 'Optimadmin::StaticPage'
      #  begin
      #    path = Object.const_get("Optimadmin::#{resource_type}").find(resource_id)
      #    path = path.route if path.present?
      #   send(path) if self.respond_to?(path)
      #  rescue
      #    nil
      #  end
      #else
      #  url_for(controller: resource_type.to_s.tableize, id: resource_id, action: 'show', only_path: true)
      #end
    end
  end
end

app/models/optimadmin/menu.rb
module Optimadmin
  class Menu

    attr_reader :name

    def initialize(name:)
      @name = name
    end

    def humanized_name
      name.humanize
    end

    def menu_items
      @menu_items ||= MenuItem.includes(link: :menu_resource).where(menu_name: name).hash_tree
    end

    def no_hash_tree_items
      @no_hash_tree ||= MenuItem.includes(link: :menu_resource).where(menu_name: name)
    end

    def self.build_collection
      NavigationMenus.map do |navigation_menu|
        Menu.new(name: navigation_menu)
      end
    end
  end
end

app/models/optimadmin/menu_item.rb
module Optimadmin
  class MenuItem < ActiveRecord::Base

    has_closure_tree order: :position, dependent: :delete_all

    validates :menu_name, presence: true, length: { maximum: 100 }
    validates :name, presence: true, length: { maximum: 100 }
    validates :title_attribute, length: { maximum: 100 }

    belongs_to :link, class_name: "Optimadmin::Link", dependent: :destroy

    accepts_nested_attributes_for :link

    before_save :check_title_attr
    before_destroy :check_last_external_link

    def self.presenter
      MenuItemPresenter
    end

    def check_title_attr
      self.title_attribute = self.name if self.title_attribute.blank? or self.name_was == self.title_attribute
    end

    def check_last_external_link
      return unless self.link.resource_type == 'Optimadmin::ExternalLink'

      # FIXME: this needs tidying maybe?
      results = Optimadmin::Link.where(resource_type: 'Optimadmin::ExternalLink', resource_id: self.link.resource_id)
      Optimadmin::ExternalLink.destroy(results.first.resource_id) if results.size == 1
    end
  end
end

app/models/optimadmin/static_page.rb
module Optimadmin
  class StaticPage < ActiveRecord::Base
    has_many :menu_items, as: :menu_resource
    validates :name, :route, presence: true, uniqueness: { case_sensitive: false }

  end
end

app/controllers/optimadmin/application_controller.rb
module Optimadmin
  class ApplicationController < ActionController::Base

    before_action :global_site_settings, :authorize

    def index
      # redirect_to optimnav_branches_path
    end

    def link_list
      respond_to do |format|
        format.js {          
          render :layout => nil
        }
      end
    end


    private

      def current_administrator
        @current_administrator ||= Administrator.find_by(auth_token: cookies[cookie_name]) if cookies[cookie_name]
      end
      helper_method :current_administrator

      def authorize
        session[cookie_name_return_to] = request.fullpath
        redirect_to login_url, alert: 'Not authorised' if current_administrator.nil?
      end

      def global_site_settings
        @global_site_settings ||= SiteSetting.current_environment
      end
      helper_method :global_site_settings

      def cookie_name
        global_site_settings['Name'] ? "#{global_site_settings['Name'].downcase.gsub(' ', '_').first(10)}_auth_token" : 'optimadmin_auth_token'
      end

      def cookie_name_return_to
        "#{cookie_name}_return_to"
      end

      # needs to be defined to use cancancan in engine
      def current_ability
        @current_ability ||= AdminAbility.new(current_administrator)
      end

    rescue_from CanCan::AccessDenied do |exception|
      logger.info exception
      flash[:error] = 'Access denied!'
      redirect_to root_url
    end
  end
end

app/controllers/optimadmin/external_links_controller.rb
module Optimadmin
  class ExternalLinksController < ApplicationController
    load_and_authorize_resource

    before_action :set_external_link, only: [:edit, :update, :destroy]

    # GET /external_links
    # GET /external_links.json
    def index
      @external_links = ExternalLink.all
    end

    # GET /external_links/new
    def new
      @external_link = ExternalLink.new
    end

    # GET /external_links/1/edit
    def edit
    end

    # POST /external_links
    # POST /external_links.json
    def create
      @external_link = ExternalLink.new(external_link_params)


        if @external_link.save
          respond_to do |format|
            format.html { redirect_to @external_link, notice: 'External link was successfully created.' }
            format.js {
              @external_link = ExternalLink.new
              flash[:notice] = 'External link was successfully created.'
              render :success
              flash.clear
            }
          end
        else
          respond_to do |format|
            format.html { render :new }
            format.js
          end
        end

    end

    # PATCH/PUT /external_links/1
    # PATCH/PUT /external_links/1.json
    def update

        if @external_link.update(external_link_params)
          redirect_to @external_link, notice: 'External link was successfully updated.'
        else
          render :edit
        end

    end

    # DELETE /external_links/1
    # DELETE /external_links/1.json
    def destroy
      @external_link.destroy
      redirect_to external_links_url, notice: 'External link was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_external_link
        @external_link = ExternalLink.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def external_link_params
        params.require(:external_link).permit(:name)
      end
  end
end

app/controllers/optimadmin/menu_items_controller.rb
module Optimadmin
  class MenuItemsController < ApplicationController
    #load_and_authorize_resource

    before_action :set_menu_item, only: [:edit, :update, :destroy]
    before_action :new_static_page, only: [:new, :create, :edit, :update]
    before_action :link_resources, only: [:edit, :update]

    def index
      @menus = Menu.build_collection
    end

    def new
      @menu_item = MenuItem.new(menu_name: params[:menu_name])
      @menu_item.build_link
      @menu_items = MenuItem.where(menu_name: params[:menu_name]).pluck(:name, :id)
    end

    def create
      @menu_item = MenuItem.new(menu_item_params)
      if @menu_item.save
        redirect_to menu_items_path, notice: "Successfully created menu item"
      else
        @link_resources = FindLinkResources.new(@menu_item.link.menu_resource_type).call
        @menu_items = MenuItem.where(menu_name: @menu_item.menu_name).pluck(:name, :id)
        render :new
      end
    end

    def edit
      @menu_items = MenuItem.where(menu_name: @menu_item.menu_name).where.not(id: @menu_item.id).pluck(:name, :id)
      @menu_item.build_link if @menu_item.link.blank?
    end

    def update
      if @menu_item.update(menu_item_params)
        redirect_to menu_items_path, notice: "Successfully created menu item"
      else
        @menu_items = MenuItem.where(menu_name: @menu_item.menu_name).where.not(id: @menu_item.id).pluck(:name, :id)
        render :edit
      end
    end

    def reorder
      @menus = Menu.build_collection
    end

    def order
      params[:item].each_with_index do |id, index|
        MenuItem.find(id).update_attribute(:position, index)
      end
      render nothing: true
    end

    def update_link_resources
      @link_resources = FindLinkResources.new(params[:klass]).call
      respond_to do |format|
        format.js
      end
    end

    def destroy
      @menu_item.destroy
      redirect_to menu_items_url, notice: 'Menu item was successfully destroyed.'
    end

    private

      def set_menu_item
        @menu_item = MenuItem.find(params[:id])
      end

      def new_static_page
        @static_page = StaticPage.new
        @external_link = ExternalLink.new
      end

      def menu_item_params
        params.require(:menu_item).permit(:menu_name, :name, :parent_id, :anchored, :new_window, :title_attribute, link_attributes: [ :menu_resource_type, :menu_resource_id, :menu_item_id ])
      end

      def link_resources
        @link_resources = FindLinkResources.new(@menu_item.link.menu_resource_type).call
      end

  end
end

app/controllers/optimadmin/static_pages_controller.rb
module Optimadmin
   class StaticPagesController < ApplicationController
    load_and_authorize_resource
    before_action :set_static_page, only: [:edit, :update, :destroy]

    # GET /static_pages
    # GET /static_pages.json
    def index
      @static_pages = StaticPage.all
    end

    # GET /static_pages/new
    def new
      @static_page = StaticPage.new
    end

    # GET /static_pages/1/edit
    def edit
    end

     # POST /static_pages
     # POST /static_pages.json
     def create
       @static_page = StaticPage.new(static_page_params)

      if @static_page.save
        respond_to do |format|
          format.html { redirect_to static_pages_url, notice: 'Static page was successfully created.' }
          format.js {
            @static_page = StaticPage.new
            flash[:notice] = 'Static page was successfully created.'
            render :success
            flash.clear
          }
        end
      else
        respond_to do |format|
          format.html { render :new }
          format.js
        end
      end
   end

    # PATCH/PUT /static_pages/1
    # PATCH/PUT /static_pages/1.json
    def update
      if @static_page.update(static_page_params)
        redirect_to static_pages_url, notice: 'Static page was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /static_pages/1
    # DELETE /static_pages/1.json
    def destroy
      @static_page.destroy
      redirect_to static_pages_url, notice: 'Static page was successfully destroyed.'
    end

     private
      # Use callbacks to share common setup or constraints between actions.
      def set_static_page
        @static_page = StaticPage.find(params[:id])
      end


       # Never trust parameters from the scary internet, only allow the white list through.
       def static_page_params
         params.require(:static_page).permit(:name, :route)
      end
  end
end

app/views/optimadmin/menu_items/_form.html.erb
<%= form_for @menu_item do |f| %>
  <%= f.hidden_field :menu_name %>

  <% if @menu_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu_item.errors.count, "error") %> prohibited this menu item from being saved:</h2>

      <ul>
        <% @menu_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= field_set_tag 'Menu Item' do %>

    <div class="field">
      <%= f.label :name %><br/>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :title_attribute %>
      <%= f.text_field :title_attribute %>
    </div>

    <div class="field">
      <%= f.label :parent_id %>
      <%= f.select :parent_id, @menu_items, include_blank: true %>
    </div>

    <div class="field">
      <%= f.label :new_window, "Open in a new window" %><br/>
      <%= f.check_box :new_window %>
    </div>

    <% if @current_administrator.role == 'master' %>
      <div class="field">
        <%= f.label :anchored do %><abbr title="Anchored menu items can not be deleted">Anchored</abbr><% end %><br />
        <%= f.check_box :anchored %>
      </div>
    <% end %>

  <% end %>

  <%= field_set_tag 'Link' do %>
    <%= f.fields_for :link do |link_fields| %>
      <%= render 'link_form', f: link_fields %>
    <% end %>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<hr />

<div class="row collapse">
  <% if can? :manage, Optimadmin::StaticPage %>
    <div class="large-3 columns">
      <div class="back">
        <%= link_to '#', class: 'toggle-class', data: { class: 'hide', container: '#new-static-page-form', return: 'true' } do %>
          <%= octicon('file-text') %>
          New Static Page
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="large-4 end columns">
    <div class="back">
      <%= link_to '#', class: 'toggle-class', data: { class: 'hide', container: '#new-external-link-form', return: 'true' } do %>
        <%= octicon('link-external') %>
        New External Link
      <% end %>
    </div>
  </div>
</div>

<div class="hide" id="new-static-page-form">
  <%= render 'optimadmin/static_pages/remote_form' %>
</div>

<div class="hide" id="new-external-link-form">
  <%= render 'optimadmin/external_links/form' %>
</div>

app/views/optimadmin/menu_items/_link_form.html.erb
<%= f.hidden_field :menu_item_id unless @menu_item.new_record? %>

<div class="field resource-type-select" data-url="<%= update_link_resources_menu_items_path %>">
  <%= f.label :menu_resource_type %>
  <%= f.select :menu_resource_type, NavigationLinks.to_a, prompt: 'Please select' %>
</div>

<% if @menu_item.link.menu_resource_type.present? %>
  <div class="field">
    <%= f.label :menu_resource_id %>
    <%= f.select :menu_resource_id, options_for_select(@link_resources, selected: @menu_item.link.menu_resource_id), {}, { prompt: 'Please select', class: 'searchable-select' } %>
  </div>
<% else %>
  <div class="field">
    <%= f.label :menu_resource_id %>
    <%= f.select :menu_resource_id, [''], {}, class: 'searchable-select' %>
  </div>
<% end %>

app/views/optimadmin/menu_items/_menu_item.html.erb
<li class="menu-item" id="item_<%= menu_item_presenter.menu_item.id %>">
  <div class="module-list-index <%= cycle('odd', 'even') %>">
    <div class="small-6 columns">
      <span class="drag-helper"></span>
      <%= menu_item_presenter.named_edit_link %>
    </div>

    <div class="small-3 columns">
      <%= menu_item_presenter.menu_resource_type %>
    </div>

    <div class="small-1 text-center columns">
      <%= menu_item_presenter.show_link %>
    </div>

    <div class="small-1 text-center columns">
      <%= menu_item_presenter.octicon_edit_link %>
    </div>

    <div class="small-1 text-center columns">
      <%= menu_item_presenter.delete_link %>
    </div>
  </div>

  <% if sub_menu_items.present? %>
    <%= content_tag :ul, class: "depth-#{ depth }" do %>
      <%= nested_admin_menu_items(menu_items: sub_menu_items, depth: depth + 1) %>
    <% end %>
  <% end %>
</li>

app/views/optimadmin/menu_items/_menu_item_tree.html.erb
<ul>
  <% menu_item_tree.each do |menu_item, menu_item_children| %>
    <li class="menu-item" id="item_<%= menu_item.id %>">
      <div class="module-list-index <%= cycle('odd', 'even') %>">
        <div class="small-6 columns">
          <span class="drag-helper"></span>

          <%= link_to menu_item.name, edit_menu_item_path(menu_item) %>
        </div>

        <div class="small-3 columns">
          <% unless menu_item.link.destination.blank? %>
            <%= menu_item.link.menu_resource_type unless menu_item.link.destination.blank? %>
          <% else %>
            <span class="dead-link">Dead link</span>
          <% end %>
        </div>

        <div class="small-1 text-center columns">
          <% unless menu_item.link.destination.blank? %>
            <%= link_to octicon('eye').html_safe, menu_item.link.destination, title: menu_item.link.menu_resource_type, class: 'menu-item-control', target: '_blank' %>
          <% else %>
            <span class="disabled">
              <%= octicon('eye') %>
            </span>
          <% end %>
        </div>

        <div class="small-1 text-center columns">
          <%= link_to octicon('pencil').html_safe, edit_menu_item_path(menu_item), class: 'menu-item-control' %>
        </div>

        <div class="small-1 text-center columns">
          <% if menu_item.anchored.present? %>
            <span class="disabled"><%= octicon('trashcan') %></span>
          <% else %>
            <%= link_to octicon('trashcan').html_safe, menu_item_path(menu_item), method: :delete, data: { confirm: 'Are you sure?' }, class: 'menu-item-control' %>
          <% end %>
        </div>
      </div>

        <% unless menu_item_children.size.zero? %>
          <ul>
            <%= render partial: "menu_item_tree", locals: { menu_item_tree: menu_item_children } %>
          </ul>
        <% end %>
    </li>
  <% end %>
</ul>

app/views/optimadmin/menu_items/edit.html.erb
<%= render 'optimadmin/shared/header/main_title', title: "Edit #{@menu_item.menu_name.humanize} Menu Item" %>

<div class="main-content">
  <%= render 'optimadmin/shared/module/form/back', path: menu_items_path, title: 'Menu Item' %>

  <%= render 'form' %>
</div>

app/views/optimadmin/menu_items/index.html.erb
<%= render 'optimadmin/shared/header/main_title', title: 'Manage Site Navigation (Menus)' %>

<div class="main-content">
  <div class="row collapse">
    <% if can? :manage, Optimadmin::StaticPage %>
      <div class="large-3 columns">
        <div class="back">
          <%= link_to static_pages_path do %>
            <%= octicon('file-text') %>
            Manage Static Pages
          <% end %>
        </div>
      </div>
    <% end %>

    <div class="large-4 end columns">
      <div class="back">
        <%= link_to reorder_menu_items_path do %>
          <%= octicon('settings') %>
          Reorder Menu Items
        <% end %>
      </div>
    </div>
  </div>


  <% @menus.each_with_index do |menu, index| %>
    <div class="row">
      <div class="small-6 columns">
        <h2><%= menu.humanized_name %></h2>
      </div>

      <div class="small-6 columns">
        <%= render 'optimadmin/shared/module/index/new_item', title: 'Menu Item', object: Optimadmin::MenuItem, path: new_menu_item_path(menu_name: menu.name) %>
      </div>
    </div>


    <% if menu.menu_items.blank? %>
      <p>This menu doesn't have any menu items yet. Use the button above to create one.</p>
    <% end %>

    <div class="menu-items-list">
      <div class="row collapse module-list-index header">

      <%= list_item 'small-6' do 'Menu item' end %>

      <%= list_item 'small-3' do 'Resource type' end %>

      <%= list_item { 'View' } %>

      <%= list_item { 'Edit' } %>

      <%= list_item { 'Delete' } %>
      </div>

      <ul>
        <%= nested_admin_menu_items(menu_items: menu.menu_items) %>
      </ul>
    </div>
  <% end %>
</div>

app/views/optimadmin/menu_items/new.html.erb
<%= render 'optimadmin/shared/header/main_title', title: "Edit #{@menu_item.menu_name.humanize} Menu Item" %>

<div class="main-content">
  <%= render 'optimadmin/shared/module/form/back', path: menu_items_path, title: 'Menu Item' %>

  <%= render 'form' %>
</div>

app/views/optimadmin/menu_items/reorder.html.erb
<%= render 'optimadmin/shared/header/main_title', title: "Reorder Menu Items" %>

<div class="main-content">
  <%= render 'optimadmin/shared/module/form/back', path: menu_items_path, title: 'Manage Menu', prefix: 'Back to' %>

  <% @menus.each do |menu| %>
    <h2><%= menu.humanized_name %></h2>

    <div class="navigation-sortable menu-items-list" data-sortable-path="<%= order_menu_items_path %>">
      <ul>
        <%= nested_admin_menu_items(menu_items: menu.menu_items) %>
      </ul>
    </div>
  <% end %>
</div>

app/views/optimadmin/menu_items/update_link_resources.js.erb
$('#menu_item_link_attributes_menu_resource_id option').remove();
$('.searchable-select').select2({data: [{id: '', text: ''}]});

<% if @link_resources.present? %>
  <% @link_resources.each do |name, id| %>
    $('#menu_item_link_attributes_menu_resource_id')
         .append($("<option></option>")
         .attr("value",<%= id %>)
         .text('<%= j name %>'));
  <% end %>
<% end %>